src/Entity/Equipo.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\EquipoRepository")
 */
class Equipo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $accesorios;
    
    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fechaCompraEquipo;
    
    
    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $n_serie;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Marca", cascade={"persist"})
     */
    private $marca;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Modelo", cascade={"persist"})
     */
    private $Modelo;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\PartNumber")
     */
    private $partnumber;
    
    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $color;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $color_lcd;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $top_cover;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $back_cover;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $observaciones;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\OrdenTrabajo", mappedBy="equipo")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $ordenestrabajo;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TipoEquipo", inversedBy="equipos")
     */
    private $tipoEquipo;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $tipo_pantalla;

    /**
     * @ORM\Column(type="string", length=4, nullable=true)
     */
    private $tiquet;


    public function __construct()
    {
        $this->ordenestrabajo = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAccesorios(): ?string
    {
        return $this->accesorios;
    }

    public function setAccesorios(?string $accesorios): self
    {
        $this->accesorios = $accesorios;

        return $this;
    }

    public function getFechaCompraEquipo(): ?\DateTimeInterface
    {
        return $this->fechaCompraEquipo;
    }

    public function setFechaCompraEquipo(?\DateTimeInterface $fechaCompraEquipo): self
    {
        $this->fechaCompraEquipo = $fechaCompraEquipo;

        return $this;
    }

    public function getNSerie(): ?string
    {
        return $this->n_serie;
    }

    public function setNSerie(?string $n_serie): self
    {
        $this->n_serie = $n_serie;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): self
    {
        $this->color = $color;

        return $this;
    }

    public function getMarca(): ?Marca
    {
        return $this->marca;
    }

    public function setMarca(?Marca $marca): self
    {
        $this->marca = $marca;

        return $this;
    }

    public function getModelo(): ?Modelo
    {
        return $this->Modelo;
    }

    public function setModelo(?Modelo $Modelo): self
    {
        $this->Modelo = $Modelo;

        return $this;
    }

    public function getPartnumber(): ?PartNumber
    {
        return $this->partnumber;
    }

    public function setPartnumber(?PartNumber $partnumber): self
    {
        $this->partnumber = $partnumber;

        return $this;
    }


    public function getColorLcd(): ?string
    {
        return $this->color_lcd;
    }

    public function setColorLcd(?string $color_lcd): self
    {
        $this->color_lcd = $color_lcd;

        return $this;
    }

    public function getTopCover(): ?string
    {
        return $this->top_cover;
    }

    public function setTopCover(?string $top_cover): self
    {
        $this->top_cover = $top_cover;

        return $this;
    }

    public function getBackCover(): ?string
    {
        return $this->back_cover;
    }

    public function setBackCover(?string $back_cover): self
    {
        $this->back_cover = $back_cover;

        return $this;
    }

    public function getObservaciones(): ?string
    {
        return $this->observaciones;
    }

    public function setObservaciones(string $observaciones): self
    {
        $this->observaciones = $observaciones;

        return $this;
    }

    /**
     * @return Collection|OrdenTrabajo[]
     */
    public function getOrdenestrabajo(): Collection
    {
        return $this->ordenestrabajo;
    }

    public function addOrdenestrabajo(OrdenTrabajo $ordenestrabajo): self
    {
        if (!$this->ordenestrabajo->contains($ordenestrabajo)) {
            $this->ordenestrabajo[] = $ordenestrabajo;
            $ordenestrabajo->setEquipo($this);
        }

        return $this;
    }

    public function removeOrdenestrabajo(OrdenTrabajo $ordenestrabajo): self
    {
        if ($this->ordenestrabajo->contains($ordenestrabajo)) {
            $this->ordenestrabajo->removeElement($ordenestrabajo);
            // set the owning side to null (unless already changed)
            if ($ordenestrabajo->getEquipo() === $this) {
                $ordenestrabajo->setEquipo(null);
            }
        }

        return $this;
    }

    public function getTipoEquipo(): ?TipoEquipo
    {
        return $this->tipoEquipo;
    }

    public function setTipoEquipo(?TipoEquipo $tipoEquipo): self
    {
        $this->tipoEquipo = $tipoEquipo;

        return $this;
    }

    public function getTipoPantalla(): ?string
    {
        return $this->tipo_pantalla;
    }

    public function setTipoPantalla(string $tipo_pantalla): self
    {
        $this->tipo_pantalla = $tipo_pantalla;

        return $this;
    }

    public function getTiquet(): ?string
    {
        return $this->tiquet;
    }

    public function setTiquet(string $tiquet): self
    {
        $this->tiquet = $tiquet;

        return $this;
    }
    
    
}

src/Form/EquipoType.php
<?php

namespace App\Form;

use App\Entity\Equipo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Modelo;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use App\Entity\PartNumber;
use App\Entity\Marca;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use App\Entity\TipoEquipo;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use App\Form\DataTransformer\PartNumberToStringTransformer;
use App\Form\DataTransformer\MarcaToStringTransformer;
use App\Form\DataTransformer\ModeloToStringTransformer;

class EquipoType extends AbstractType
{
    private $transformer;
    private $marca;
    private $modelo;

    
    
    public function __construct(PartNumberToStringTransformer $transformer, MarcaToStringTransformer $mTransform, ModeloToStringTransformer $moTransformer)
    {
        $this->transformer = $transformer;
        $this->marca = $mTransform;
        $this->modelo = $moTransformer;

    }
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
      
        
        $builder
            ->add('tipo_equipo',EntityType::class,[
                "class"=>TipoEquipo::class,
                "choice_label"=>"nombre",
                "multiple"=>false,
                "expanded"=>true
            ])
            ->add('n_serie', TextType::class,["label"=>"Número de serie"])
            ->add('color', TextType::class, ["label"=>"Color Base"])
            ->add('observaciones')
            ->add('partnumber', TextType::class)
            ->add('marca', TextType::class
                )
            ->add('color_lcd')
            ->add('top_cover',TextType::class,["label"=>"Top Cover / Marco de Movil"])
            ->add('back_cover', TextType::class,["label"=>"Back"])
            ->add('Modelo', TextType::class)
                ->add('tipo_pantalla',ChoiceType::class,["choices"=>[
                    "Selecciona una"=>null,
                    "Glossy"=>"glossy",
                    "Mate"=>"Mate",
                    "Táctil"=>"tactil"
                ]]
                    )
            ->add("tiquet", TextType::class,["label"=>"Tíquet Equipo","attr"=>["maxlenght"=>4]])    
            ->add('fechaCompraEquipo',DateTimeType::class, array("widget"=>"single_text","format"=>"dd/MM/yyyy","attr"=>["autocomplete"=>"off"])
                )
                    
        ;
                
         $builder->get('partnumber')
            ->addModelTransformer($this->transformer);
            $builder->get('marca')
            ->addModelTransformer($this->marca);
            $builder->get('Modelo')
            ->addModelTransformer($this->modelo);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Equipo::class,
        ]);
    }
}

src/Controller/Admin/EquipoController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Equipo;
use App\Form\EquipoType;
use App\Repository\EquipoRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

/**
 * @Route("/equipo")
 * @IsGranted("ROLE_TECNIC")
 */
class EquipoController extends AbstractController
{
    /**
     * @Route("/", name="equipo_index", methods={"GET"})
	 * * @IsGranted("ROLE_CENTRAL")
     */
    public function index(EquipoRepository $equipoRepository): Response
    {
        return $this->render('equipo/index.html.twig', [
            'equipos' => $equipoRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="equipo_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $equipo = new Equipo();
        $form = $this->createForm(EquipoType::class, $equipo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($equipo);
            $entityManager->flush();

            return $this->redirectToRoute('equipo_index');
        }

        return $this->render('equipo/new.html.twig', [
            'equipo' => $equipo,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="equipo_show", methods={"GET"})
     */
    public function show(Equipo $equipo): Response
    {
        return $this->render('equipo/show.html.twig', [
            'equipo' => $equipo,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="equipo_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Equipo $equipo): Response
    {
        $form = $this->createForm(EquipoType::class, $equipo);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('equipo_index', [
                'id' => $equipo->getId(),
            ]);
        }

        return $this->render('equipo/edit.html.twig', [
            'equipo' => $equipo,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="equipo_delete", methods={"DELETE"})
     * @IsGranted("ROLE_CENTRAL")
     */
    public function delete(Request $request, Equipo $equipo): Response
    {
        if ($this->isCsrfTokenValid('delete'.$equipo->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($equipo);
            $entityManager->flush();
        }

        return $this->redirectToRoute('equipo_index');
    }
}

templates/equipo/_delete_form.html.twig
<form method="post" action="{{ path('equipo_delete', {'id': equipo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ equipo.id) }}">
    <button class="btn">Delete</button>
</form>

templates/equipo/_form.html.twig
{{ form_start(form) }}
    <div class="row">
		<div class="col">
            {{ form_row(form.n_serie,{"required":"false"}) }}
        </div>
        <div class="col">
            {{ form_row(form.partnumber,{"required":"false"}) }}
        </div>
        <div class="col">
            {{ form_row(form.marca,{"required":"false"}) }}
        </div>
        <div class="col">
            {{ form_row(form.Modelo,{"required":"false"}) }}
        </div>  
    </div>
    <div class="row">
            
            <div class="col">
                {{ form_row(form.color,{"required":"false"}) }}
            </div>
            <div class="col">
            	{{ form_row(form.color_lcd,{"required":"false"}) }}
            </div>
            <div class="col">
            	{{ form_row(form.back_cover,{"required":"false"}) }}
            </div> 
            <div class="col">
            	{{ form_row(form.top_cover,{"required":"false"}) }}
            </div> 
            <div>
                {{form_row(form.FechaCompraEquipo,{"required":"false"})}}
            </div>
            
        </div>
        {{ form_row(form.observaciones) }}
        <button class="btn btn-primary" type="submit">Guardar</button>
{{ form_end(form) }}

templates/equipo/edit.html.twig
{% extends 'master.html.twig' %}

{% block content %}
    <h1>Equipo {{ equipo.nserie }}</h1>

    {{ include('equipo/_form.html.twig', {'button_label': 'Update'}) }}
    <h4>Ordenes con este dispositivo</h4>
    <table class="table">
    	<tr>
    		<th scope="col">Orden</th>
    		<th scope="col">Fecha Entrada</th>
    		<th scope="col">Fecha Salida</th>
    	</tr>
		{% for orden in equipo.ordenestrabajo %}
		<tr>
			<td>
				<a href="{{ path('ordentrabajo_edit',{'id':orden.id}) }}">{{ orden.norden }}</a>
			</td>
			<td>{{ orden.fechaEntrada|date("d/m/Y") }}</td>
			<td>{{ orden.fechaSalida|date("d/m/Y") }}</td>
		</tr>
		{% endfor %}
	</table>
    <a href="{{ path('equipo_index') }}">back to list</a>

    {{ include('equipo/_delete_form.html.twig') }}
{% endblock %}

templates/equipo/index.html.twig
{% extends 'master.html.twig' %}

{% block title %}Equipo index{% endblock %}

{% block content %}
    <h1>Equipo index</h1>

    <table class="table">
        <thead>
            <tr>
            	<th>Nº Serie</th>
            	<th>Marca / Modelo</th>
            	<th>Part Number</th>
                <th>FechaCompraEquipo</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for equipo in equipos %}
            <tr>
           	 	<td>{{ equipo.nSerie }}</td>
           	 	<td>{% if equipo.Marca %} {{ equipo.Marca.nombre }} / {{ equipo.Modelo.nombre }} {% else %} Sin Marca Registrada {% endif %}</td>
                <td> En desarrollo</td>
                <td>{{ equipo.fechaCompraEquipo ? equipo.fechaCompraEquipo|date('d/m/Y') : '' }}</td>
                <td>
                    <a class="btn btn-primary btn-sm" href="{{ path('equipo_edit', {'id': equipo.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('equipo_new') }}">Create new</a>
{% endblock %}

templates/equipo/new.html.twig
{% extends 'master.html.twig' %}

{% block title %}New Equipo{% endblock %}

{% block content %}
    <h1>Create new Equipo</h1>

    {{ include('equipo/_form.html.twig') }}

    <a href="{{ path('equipo_index') }}">back to list</a>
{% endblock %}

templates/equipo/show.html.twig
{% extends 'master.html.twig' %}

{% block title %}Equipo{% endblock %}

{% block content %}
    <h1>Equipo</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ equipo.id }}</td>
            </tr>
            <tr>
                <th>Accesorios</th>
                <td>{{ equipo.accesorios }}</td>
            </tr>
            <tr>
                <th>FechaCompraEquipo</th>
                <td>{{ equipo.fechaCompraEquipo ? equipo.fechaCompraEquipo|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>N_serie</th>
                <td>{{ equipo.nSerie }}</td>
            </tr>
            <tr>
                <th>Color</th>
                <td>{{ equipo.color }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('equipo_index') }}">back to list</a>

    <a href="{{ path('equipo_edit', {'id': equipo.id}) }}">edit</a>

    {{ include('equipo/_delete_form.html.twig') }}
{% endblock %}