src/Entity/Ordentrabajo.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrdentrabajoRepository")
 */
class Ordentrabajo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Serie", inversedBy="ordentrabajos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $serie;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Usuario", inversedBy="ordentrabajos")
     */
    private $usuarios;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $indicaciones_cliente;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $averias_detectadas;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Delegacion", inversedBy="ordentrabajos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $delegacion;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Prioridad", inversedBy="ordentrabajos")
     * @ORM\JoinColumn(nullable=true)
     */
    private $prioridad;
    
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Tipo", inversedBy="ordentrabajos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tipo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $fecha_entrada;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fecha_salida;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $fecha_fin;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $PresupuestoAceptado;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Actualizar = false;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Situacion", inversedBy="ordentrabajos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $situacion;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $n_orden;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $n_caso;

    

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $TrabajosaRealizar;


    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Materiales", mappedBy="OrdenTrabajo", cascade="persist")
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private $materiales;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $observaciones;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $observaciones_int;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $n_presupuesto;
    
    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $accesorios;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Tiquets", inversedBy="ordentrabajo", cascade={"persist", "remove"})
     */
    private $tiquet;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Equipo", inversedBy="ordenestrabajo", cascade={"PERSIST"})
     */
    private $equipo;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\CierreReparaciones", mappedBy="Reparacion", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=true)
     */
    private $cierreReparaciones;


    /**
     * @return mixed
     */
    public function getAccesorios() : ?string
    {
        return $this->accesorios;
    }

    /**
     * @param mixed $accesorios
     */
    public function setAccesorios(string $accesorios) : self
    {
        $this->accesorios = $accesorios;
        
        return $this;
    }

    public function __construct()
    {
        $this->usuarios = new ArrayCollection();
        $this->fecha_entrada = new \DateTime();
        $this->fecha_salida = null;
        $this->materiales = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSerie(): ?Serie
    {
        return $this->serie;
    }

    public function setSerie(?Serie $serie): self
    {
        $this->serie = $serie;

        return $this;
    }

    /**
     * @return Collection|Usuario[]
     */
    public function getUsuarios(): Collection
    {
        return $this->usuarios;
    }

    public function addUsuario(Usuario $usuario): self
    {
        if (!$this->usuarios->contains($usuario)) {
            $this->usuarios[] = $usuario;
        }

        return $this;
    }

    public function removeUsuario(Usuario $usuario): self
    {
        if ($this->usuarios->contains($usuario)) {
            $this->usuarios->removeElement($usuario);
        }

        return $this;
    }

    public function getIndicacionesCliente(): ?string
    {
        return $this->indicaciones_cliente;
    }

    public function setIndicacionesCliente(?string $indicaciones_cliente): self
    {
        $this->indicaciones_cliente = $indicaciones_cliente;

        return $this;
    }

    public function getAveriasDetectadas(): ?string
    {
        return $this->averias_detectadas;
    }

    public function setAveriasDetectadas(?string $averias_detectadas): self
    {
        $this->averias_detectadas = $averias_detectadas;

        return $this;
    }

    public function getDelegacion(): ?Delegacion
    {
        return $this->delegacion;
    }

    public function setDelegacion(?Delegacion $delegacion): self
    {
        $this->delegacion = $delegacion;

        return $this;
    }

    public function getPrioridad(): ?Prioridad
    {
        return $this->prioridad;
    }

    public function setPrioridad(?Prioridad $prioridad): self
    {
        $this->prioridad = $prioridad;

        return $this;
    }

    

    public function getTipo(): ?Tipo
    {
        return $this->tipo;
    }

    public function setTipo(?Tipo $tipo): self
    {
        $this->tipo = $tipo;

        return $this;
    }

    public function getFechaEntrada(): ?\DateTimeInterface
    {
        return $this->fecha_entrada;
    }

    public function setFechaEntrada(?\DateTimeInterface $fecha_entrada): self
    {
        $this->fecha_entrada = $fecha_entrada;

        return $this;
    }

    public function getFechaSalida(): ?\DateTimeInterface
    {
        return $this->fecha_salida;
    }

    public function setFechaSalida(?\DateTimeInterface $fecha_salida): self
    {
        $this->fecha_salida = $fecha_salida;

        return $this;
    }

    public function getFechaFin(): ?\DateTimeInterface
    {
        return $this->fecha_fin;
    }

    public function setFechaFin(?\DateTimeInterface $fecha_fin): self
    {
        $this->fecha_fin = $fecha_fin;

        return $this;
    }

    public function getPresupuestoAceptado(): ?bool
    {
        return $this->PresupuestoAceptado;
    }

    public function setPresupuestoAceptado(bool $PresupuestoAceptado): self
    {
        $this->PresupuestoAceptado = $PresupuestoAceptado;

        return $this;
    }

    public function getActualizar(): ?bool
    {
        return $this->Actualizar;
    }

    public function setActualizar(?bool $Actualizar): self
    {
        $this->Actualizar = $Actualizar;

        return $this;
    }

    public function getSituacion(): ?Situacion
    {
        return $this->situacion;
    }

    public function setSituacion(?Situacion $situacion): self
    {
        $this->situacion = $situacion;

        return $this;
    }

    public function getNOrden(): ?string
    {
        return $this->n_orden;
    }

    public function setNOrden(?string $n_orden): self
    {
        $this->n_orden = $n_orden;

        return $this;
    }

    public function getNCaso(): ?string
    {
        return $this->n_caso;
    }

    public function setNCaso(string $n_caso): self
    {
        $this->n_caso = $n_caso;

        return $this;
    }

    
    public function getTrabajosaRealizar(): ?string
    {
        return $this->TrabajosaRealizar;
    }

    public function setTrabajosaRealizar(?string $TrabajosaRealizar): self
    {
        $this->TrabajosaRealizar = $TrabajosaRealizar;

        return $this;
    }

    public function getNSerie(): ?string
    {
        return $this->n_serie;
    }

    public function setNSerie(?string $n_serie): self
    {
        $this->n_serie = $n_serie;

        return $this;
    }

    /**
     * @return Collection|Materiales[]
     */
    public function getMateriales(): Collection
    {
        return $this->materiales;
    }

    public function addMateriale(Materiales $materiale): self
    {
        if (!$this->materiales->contains($materiale)) {
            $this->materiales[] = $materiale;
            $materiale->setOrdenTrabajo($this);
        }

        return $this;
    }

    public function removeMateriale(Materiales $materiale): self
    {
        if ($this->materiales->contains($materiale)) {
            $this->materiales->removeElement($materiale);
            // set the owning side to null (unless already changed)
            if ($materiale->getOrdenTrabajo() === $this) {
                $materiale->setOrdenTrabajo(null);
            }
        }

        return $this;
    }

    public function getObservaciones(): ?string
    {
        return $this->observaciones;
    }

    public function setObservaciones(?string $observaciones): self
    {
        $this->observaciones = $observaciones;

        return $this;
    }

    public function getObservacionesInt(): ?string
    {
        return $this->observaciones_int;
    }

    public function setObservacionesInt(?string $observaciones_int): self
    {
        $this->observaciones_int = $observaciones_int;

        return $this;
    }

    public function getNPresupuesto(): ?string
    {
        return $this->n_presupuesto;
    }

    public function setNPresupuesto(?string $n_presupuesto): self
    {

src/Form/OrdentrabajoType.php
<?php

namespace App\Form;

use App\Entity\Ordentrabajo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateType;

use App\Entity\Serie;
use App\Entity\Situacion;
use App\Entity\Usuario;
use App\Entity\Marca;
use App\Entity\Modelo;
use App\Entity\PartNumber;
use App\Entity\Prioridad;
use App\Entity\Tipo;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use App\Form\DataTransformer\PartNumberToStringTransformer;
use App\Form\DataTransformer\MarcaToStringTransformer;
use Doctrine\Common\Collections\Collection;
use App\Form\DataTransformer\ModeloToStringTransformer;

class OrdentrabajoType extends AbstractType
{
   
    
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        
        
        $builder
            ->add('n_caso',null,array("label"=>"Número de caso","attr"=>["maxlength"=>8]))
            ->add('tiquet',TiquetsType::class, ["label"=>"Tiquet Diagnóstico"])
            ->add('situacion', EntityType::class,
            [
                "class"=>Situacion::class,
                "choice_label"=>"nombre",
            ]
            )
            ->add('n_orden',null,array("label"=>"Número de orden","attr"=>array("readonly"=>true)))
            ->add('fecha_entrada', DateTimeType::class, array("widget"=>"single_text","format"=>"dd/MM/yyyy","attr"=>["autocomplete"=>"off"]))
            ->add('indicaciones_cliente', TextareaType::class,
            [
                "attr"=>[
                            "rows"=>5
                        ]

            ])
            ->add('averias_detectadas', TextareaType::class,[
                "attr"=>[
                    "rows"=>5
                ],
                "label"=>"Averias detectadas / Diagnóstico"
            ])
            ->add('TrabajosaRealizar', TextareaType::class,[
                "label"=>"Trabajos a realizar / Piezas a solicitar",
                "required"=>false,
                "attr"=>[
                    "rows"=>5
                ]
            ])
            ->add('accesorios')
            ->add('usuarios', EntityType::class, 
                    [
                        'class'=>Usuario::class,
                        'choices'=> $options["data"]->getDelegacion() ? $options["data"]->getDelegacion()->getUsuarios() : $options["user"]->getDelegacion()->getUsuarios(),
                        'choice_label' => 'nombre',
                        'multiple'     => true,
                        'expanded'=>true,
                        "label"=>"Técnicos:"
                    ])
            ->add('prioridad', EntityType::class, 
                    [
                        'class'=>Prioridad::class,
                        'choice_label' => 'nombre',
                        'choice_value' => 'id',
                    ])
            ->add('observaciones',TextareaType::class,[
                'attr'=>[
                    'size'=>'90','maxlength'=>'90',"autocomplete"=>"off"
                ],
                "required"=>false
            ])
            ->add('observaciones_int',TextareaType::class,[
                "label"=> "Observaciones Internas",
                "required" => false,
            ])
            ->add('equipo', EquipoType::class)
            ;  
            
            
            
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Ordentrabajo::class,
            'user'=>null
        ]);
    }
}

templates/ordentrabajo/_delete_form.html.twig
<form method="post" action="{{ path('ordentrabajo_delete', {'id': ordentrabajo.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ordentrabajo.id) }}">
    <button class="btn">Delete</button>
</form>

templates/ordentrabajo/_form.html.twig
{{ form_start(form) }}
	<div class="row">
		<div class="col">
			<div class="row">
    			<div class="col">
    			{{ form_row(form.tiquet.numero,{"required":false}) }}
    			</div>
    			<div class="col">
    			{{ form_row(form.tiquet.fecha,{"required":false}) }}
    			</div>
    			<div class="col">
    			{{ form_row(form.tiquet.Cupon,{"label":"Cheque Diagnostico (sin tiquet)"}) }}
    			{{ form_row(form.tiquet.cobrado,{"label":"Tiquet NO Cobrado"}) }}
    			</div>
			</div>
		</div>
	</div>
    <div class="row">
        <div class="col-md-6">
                {{ form_row(form.n_caso) }}
                
        </div>
        <div class="col-md-6">
        {% if is_granted("ROLE_CENTRAL") %}
                {{ form_row(form.situacion) }}
            {% else %}
            	{{ form_row(form.situacion,{"attr":{"disabled":"disabled"}}) }}
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col">
                {{form_row(form.n_orden)}}
        </div>
        <div class="col">
            {% if is_granted("ROLE_CENTRAL") %}
                {{ form_row(form.prioridad) }}
            {% else %}
            	{{ form_row(form.prioridad,{"attr":{"disabled":"disabled"}}) }}
            {% endif %}
        </div>
        <div class="col">
            <label for="ordentrabajo_fecha_entrada_date">Fecha Entrada</label>
            {{ form_widget(form.fecha_entrada) }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ form_row(form.indicaciones_cliente) }}
        </div>
        <div class="col">
            {{ form_row(form.averias_detectadas) }}
        </div>
    </div>
    <div class="row">
        <div class="col">
            {{ form_row(form.usuarios) }}
        </div>
        <div class="col">
            {{ form_row(form.TrabajosaRealizar) }}
        </div>
    </div>
    <div class="row">
            <div class="col">
                {{ form_row(form.observaciones) }}
            </div>
            <div class="col">
                {{ form_row(form.observaciones_int) }}
            </div>
        </div>
    <h1>Equipo a reparar</h1>
    {{ form_row(form.equipo.tipo_equipo,{"required":false}) }}
     <div class="row">
		<div class="col">
            {{ form_row(form.equipo.n_serie,{"required":false}) }}
        </div>
        <div class="col">
            {{ form_row(form.equipo.partnumber,{"required":false}) }}
        </div>
        <div class="col">
            {{ form_row(form.equipo.marca,{"required":false}) }}
        </div>
        <div class="col">
            {{ form_row(form.equipo.Modelo,{"required":false}) }}
        </div>  
    </div>
    <div class="row">
            
            <div class="col">
                {{ form_row(form.equipo.color,{"required":false}) }}
            </div>
            <div class="col">
            	{{ form_row(form.equipo.color_lcd,{"required":false}) }}
            </div>
            <div class="col">
            	{{ form_row(form.equipo.back_cover,{"required":false}) }}
            </div> 
            <div class="col">
            	{{ form_row(form.equipo.top_cover,{"required":false}) }}
            </div> 
            <div>
                {{form_row(form.equipo.fechaCompraEquipo,{"required":false})}}
            </div>
            
        </div>
   		<div class="row">
   			<div class="col">{{form_row(form.equipo.tiquet,{"required":false})}}</div>
   			<div class="col">{{form_row(form.equipo.tipo_pantalla,{"required":false})}}</div>
   		</div>
   		<div class="row">
   			<div class="col">{{form_row(form.accesorios,{"required":false})}}</div>
   		</div>
        {{ form_row(form.equipo.observaciones,{"label":"Observaciones sobre el Equipo a reparar"}) }}
    <div class="row">

        </div>
        <a href="{{ path("ordentrabajo_index") }}" class="btn btn-primary">Salir</a>
{{ form_end(form) }}

templates/ordentrabajo/index.html.twig
{% extends 'master.html.twig' %}

{% block title %}Ordentrabajo index{% endblock %}

{% block content %}
    <a class="btn btn-primary" href="{{ path("ordentrabajo_new") }}">Nueva Orden</a>{% if is_granted("ROLE_USER") and is_granted("ROLE_CENTRAL") == false %} <a class="btn btn-warning" href="{{path("ordentrabajo_update_clinica")}}">Actualizar mi clinica</a> {% endif %}{% if is_granted("ROLE_CENTRAL") %} <a class="btn btn-danger" href="{{path("ordentrabajo_update_all")}}">Actualizar Todas</a> {% endif %}
    {% if maxPages > 1 %}
        <nav aria-label="Page navigation">
            <ul class="pagination">
            {%if thisPage > 1 %}
                <li class="page-item">
                    <a class="page-link" href="{{ path('ordentrabajo_index', app.request.query.all|merge({page:thisPage-1 < 1 ? 1 : thisPage-1}))}}">«</a>
                </li>
            {% endif %}

            {# Render each page number #}
            {% for i in 1..maxPages %}
                <li class="page-item">
                    <a class="page-link" href="{{ path('ordentrabajo_index', app.request.query.all|merge({"page":i}))}}">{{ i }}</a>
                </li>
            {% endfor %}

            {# `»` arrow #}
            {%if thisPage < maxPages %}
                <li class="page-item">
                    <a class="page-link" href="{{ path('ordentrabajo_index', app.request.query.all|merge({page:thisPage+1 <= maxPages ? thisPage+1 : thisPage})) }}">»</a>
                </li>
            {% endif %}
        </ul>
        </nav>
    {% endif %}
    {% if app.request.queryString %}
    <div class="row mt-3">
        {% if app.request.get("tipo") %}
        	<a class="btn btn-danger btn-sm ml-3" href="{{ path("ordentrabajo_index",app.request.query.all|merge({"tipo":null,"delegacion":app.request.get("delegacion"),"situacion":app.request.get("situacion")})) }}">Borrar filtro Tipo  <i class="fa fa-times"></i></a>  
        {% endif %}
        {% if app.request.get("delegacion") %}
        	<a class="btn btn-danger btn-sm ml-3" href="{{ path("ordentrabajo_index",app.request.query.all|merge({"tipo":app.request.get("tipo"),"delegacion":null,"situacion":app.request.get("situacion")})) }}">Borrar filtro Delegación  <i class="fa fa-times"></i></a>  
        {% endif %}
        {% if app.request.get("situacion") %}	
        	<a class="btn btn-danger btn-sm ml-3" href="{{ path("ordentrabajo_index",app.request.query.all|merge({"tipo":app.request.get("tipo"),"delegacion":app.request.get("delegacion"),"situacion":null})) }}">Borrar filtro Situación  <i class="fa fa-times"></i></a>  
        {% endif %}
    </div>
    {% endif %}
    
    <table class="table">
        <thead>
            <tr>
                <th>Nº Caso</th>
                <th>Nº Orden</th>
                <th>
                    <ul class="nav in" id="side-menu">
                        <li class="">
                            <a data-toggle="dropdown" href="#">Tipo<span class="fa arrow"></span></a>
                            <ul class="dropdown-menu" id="tipo" aria-expanded="false">
                            
                            {% set parameters = app.request.query.all %}
                                {% for tipo in tipos %}
                                	<li class="dropdown-item">
                        	 			<a href="{{ path("ordentrabajo_index",{"tipo":tipo.id}|merge({"delegacion":app.request.get("delegacion"),"situacion":app.request.get("situacion")})) }}">{{ tipo.nombre }} </a>
                                	 </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </th>
                <th>
                    <ul class="nav in" id="side-menu">
                    	<li class="">
                            <a data-toggle="dropdown" href="#">Delegacion<span class="fa arrow"></span></a>
                            <ul class="dropdown-menu" id="delegacion" aria-expanded="false">
                                {% for delegacion in delegaciones %}
                                	<li class="dropdown-item">
                                	 	<a href="{{ path("ordentrabajo_index",{"delegacion":delegacion.id}|merge({"situacion":app.request.get("situacion"),'tipo':app.request.get("tipo")})) }}">{{ delegacion.nombre }} </a>
                                	 </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </th>
                <th>
                	<ul class="nav in" id="side-menu">
                    	<li class="">
                            <a data-toggle="dropdown" href="#">Situacion<span class="fa arrow"></span></a>
                            <ul class="dropdown-menu" id="delegacion" aria-expanded="false">
                                {% for situacion in situaciones %}
                                	<li class="dropdown-item">
                                	 	<a href="{{ path("ordentrabajo_index",{"situacion":situacion.id}|merge({"delegacion":app.request.get("delegacion"),'tipo':app.request.get("tipo")})) }}">{{ situacion.nombre }}</a>
                                	 </li>
                                {% endfor %}
                            </ul>
                        </li>
                    </ul>
                </th>
                <th>Fecha_entrada</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
        {% for ordentrabajo in ordentrabajos %}
            <tr>
                <td><a href="{{ path('ordentrabajo_edit', {'n_orden': ordentrabajo.norden}) }}">{{ ordentrabajo.ncaso }}</a></td>
                <td>{{ ordentrabajo.norden }}</td>
                <td><a href="{{path("ordentrabajo_index",app.request.query.all|merge({"tipo":ordentrabajo.tipo.id}))}}">{{ ordentrabajo.tipo.nombre }}</a></td>
                <td><a href="{{path("ordentrabajo_index",app.request.query.all|merge({"delegacion":ordentrabajo.delegacion.id}))}}">{{ ordentrabajo.delegacion.nombre }}</a></td>
                <td><a href="{{path("ordentrabajo_index",app.request.query.all|merge({"situacion":ordentrabajo.situacion.id}))}}">{{ ordentrabajo.situacion.nombre }}</a></td>
                <td>{{ ordentrabajo.fechaEntrada ? ordentrabajo.fechaEntrada|date('d-m-Y') : '' }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('ordentrabajo_edit', {'n_orden': ordentrabajo.norden}) }}">Ver</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9"><strong>No se han encontrado ordenes</strong>, prueba a buscar una por número de caso o número de orden, si existe en nuestro sistema te aparecerá su estado actual.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/ordentrabajo/new.html.twig
{% extends 'master.html.twig' %}

{% block title %}Nuevo caso{% endblock %}

{% block content %}
    <div class="row mb-4">
    	<div class="col">
    		<h2>Nueva Reparación</h2>
        	<a class="btn btn-primary" href="{{ path("ordentrabajo_new",{"tipo":"presupuesto"}) }}"><strong>Presupuesto</strong></a>
    		 o <a class="btn btn-success" href="{{ path("ordentrabajo_new",{"tipo":"wty"}) }}"><strong>Garantía</strong></a>
    	</div>
    	
    </div>
{% endblock %}

templates/ordentrabajo/show.html.twig
{% extends 'master.html.twig' %}

{% block title %}Ordentrabajo{% endblock %}

{% block content %}
    <h1>Orden {{ordentrabajo.ncaso}}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Nº Orden Central</th>
                <td>{{ ordentrabajo.norden }}</td>
            </tr>
            <tr>
                <th>Delegación</th>
                <td>{{ ordentrabajo.delegacion.nombre }}</td>
            </tr>
            <tr>
                <th>Tipo</th>
                <td>{{ ordentrabajo.tipo.nombre }}</td>
            </tr>
            <tr>
                <th>Situación</th>
                <td>{{ ordentrabajo.situacion.nombre }}</td>
            </tr>
            <tr>
                <th>Fecha Entrada</th>
                <td>{{ ordentrabajo.fechaEntrada ? ordentrabajo.fechaEntrada|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Fecha Salida</th>
                <td>{{ ordentrabajo.fechaSalida ? ordentrabajo.fechaSalida|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Fecha Fin</th>
                <td>{{ ordentrabajo.fechaFin ? ordentrabajo.fechaFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Indicaciones Cliente</th>
                <td>{{ ordentrabajo.indicacionesCliente }}</td>
            </tr>
            <tr>
                <th>Averias Detectadas</th>
                <td>{{ ordentrabajo.averiasDetectadas }}</td>
            </tr>
            <tr>
                <th>Trabajos a realizar</th>
                <td>{{ ordentrabajo.trabajosarealizar }}</td>
            </tr>
            <tr>
                <th>Observaciones</th>
                <td>{{ ordentrabajo.observaciones }}</td>
            </tr>
            <tr>
                <th>Observaciones Internas</th>
                <td>{{ ordentrabajo.observacionesInt }}</td>
            </tr>
            
            <tr>
                <th>Operarios</th>
                <td>
                    {% for usuario in ordentrabajo.usuarios %}
                        {{ usuario.nombre}}
                    {% endfor %}
                </td>
            </tr>
        </tbody>
    </table>       
    {% if ordentrabajo.materiales %}
        <h1>Materiales Presupestados</h1>
        <table class="table">
            {% for material in ordentrabajo.materiales %}
                <tr>
                    <th>Articulo</th>
                    <td>{{material.nombre}}</td>
                </tr>
            {% endfor %}
        </table>
    {% endif %}

{% endblock %}